import{i as L,a as te}from"./assets/skroll-btn-f86a557c.js";import{T as N,i as o,a as b}from"./assets/vendor-29bef8ec.js";const se=document.querySelector(".quote-info"),U="quote-of-the-day",T="date",ne=new Date,E=ne.getDate();async function ae(){try{const n=(await b.create({baseURL:"https://energyflow.b.goit.study/api"}).get("/quote")).data;_(n),re(n,E)}catch(e){o.error({timeout:5e3,title:"Error",message:e.message,position:"topRight"})}}//! SAVE QUOTE AND DATA
function re(e,t){localStorage.setItem(U,JSON.stringify(e)),localStorage.setItem(T,t)}//! RENDER QUOTE
function _(e){const t=[e];se.innerHTML=t.reduce((n,{quote:s,author:c})=>n+`<p class="quote-text">${s}</p>
        <h3 class="quote-author">${c}</h3>`,"")}//! CHECK DAY AND GET NEW QUOTE
async function oe(){const e=localStorage.getItem(T);if(isNaN(e)){o.error({timeout:5e3,title:"Error",message:error.message,position:"topRight"});return}if(parseInt(e)===E){const t=localStorage.getItem(U);if(t){const n=JSON.parse(t);_(n)}return}await ae(),localStorage.setItem(T,E.toString())}oe();//! ANIMATION 
new N("#quote",{speed:26,startDelay:300,waitUntilVisible:!0,afterComplete:function(e){e.destroy()}}).go();new N("#motivation-txt",{speed:26,startDelay:300,waitUntilVisible:!0,afterComplete:function(e){e.destroy()}}).go();const ie=document.querySelector(".waist-pagination"),ce=document.querySelector(".filter-list"),P=document.querySelector(".gallery"),h=document.querySelector(".pagination-btn"),W=document.querySelector(".waist"),V=document.querySelector(".field-search-wraper"),F=document.querySelector("#slash"),le=b.create({baseURL:"https://energyflow.b.goit.study/api"});let D;const ue=document.querySelector('button[name="Muscles"]');document.addEventListener("DOMContentLoaded",async()=>{await k({filter:"Muscles"}),ue.classList.add("filter-active")});const de=async({filter:e,page:t,limit:n})=>{try{return D=await le.get("/filters",{params:{filter:e,page:t,limit:n}}),D}catch(s){o.error({message:s.message,color:"red",position:"topCenter"})}};ce.addEventListener("click",e=>{e.preventDefault(),P.innerHTML="",h.innerHTML="",W.innerHTML="",F.innerHTML="",V.style="display:none",ie.innerHTML="",e.target.tagName==="BUTTON"&&(document.querySelectorAll(".filter-button").forEach(t=>{t.classList.remove("filter-active")}),e.target.classList.add("filter-active"),k({filter:e.target.name}))});h.addEventListener("click",e=>{e.preventDefault(),W.innerHTML="",h.innerHTML="",P.innerHTML="",F.innerHTML="",V.style="display:none",e.target.tagName==="BUTTON"&&k({filter:e.target.name,page:e.target.id})});async function k({filter:e,page:t=1,limit:n=12}){try{const s=await de({filter:e,page:t,limit:n}),c=()=>{const m=s.data.totalPages;let i="";for(let r=1;r<=m;r++)Number(t)===r?i+=`<li id="${r}"  class="pg-item" > <button id="${r}" class="pg-num-btn pg-num-btn-active" type="button" name="${e}"
 >${r}</button></li> `:i+=`<li id="${r}"  class="pg-item" > <button id="${r}" class="pg-num-btn" type="button" name="${e}"
 >${r}</button></li> `;return i},d=s.data.results.reduce((m,{name:i,filter:r,imgUrl:ee})=>m+`<li class="gallery-item" id=${i}>
          <div class="card" id="${r}:${i}">
             <img class="gallery-image"
             src="${ee}"
             alt="${r}"
            />
            </div>
            <div class="card-description" id="${r}:${i}">
            <p class="name-description" id="${r}:${i}">${i}</p>
            <p class="filter-description" id="${r}:${i}">${r}</p>
            </div>
          </li>`,""),M=c();h.innerHTML=M,P.innerHTML=d}catch(s){console.error(s),o.error({message:s.message,color:"red",position:"topCenter"})}}const pe="Unfortunately, no results were found. You may want to consider other search options to find the exercise you are looking for. Our range is wide and you have the opportunity to find more options that suit your needs.",ge=document.querySelector(".field-search-wraper"),me=document.querySelector(".exercises-wraper"),w=document.querySelector(".gallery"),ye=document.querySelector(".search-icon");let fe=document.querySelector("#slash");const p=document.querySelector(".waist"),G=document.querySelector("#search"),he=document.querySelector(".pagination-btn"),z=document.querySelector(".waist-pagination"),A=innerWidth;let a,q,Q=1,y;const v=b.create({baseURL:"https://energyflow.b.goit.study/api"}),I=async(e,{params:t})=>await v.get(e,{params:t});w.addEventListener("click",e=>{e.preventDefault(),y=0,!(e.target.nodeName!=="DIV"&&e.target.nodeName!=="H3"&&e.target.nodeName!=="P")&&(z.innerHTML="",he.innerHTML="",p.innerHTML="",w.innerHTML="",fe.innerHTML="",ge.style.display="block",p.classList.add("information-cards"),q=e.target.id,a=q.split(":"),v.defaults.params={page:Q,limit:A>1400?"9":"8",muscles:a[0]==="Muscles"?a[1]:null,bodypart:a[0]==="Body parts"?a[1]:null,equipment:a[0]==="Equipment"?a[1]:null},be())});let S="";function be(){I("/exercises",{params:{}}).then(e=>{y=e.data.totalPages;const n=(()=>{for(let s=1;s<=y;s++)Number(Q)===s?S+=`<li id="${s}"  class="pg-item" > <button id="${s}" class="pg-num-btn pg-num-btn-active" type="button"
 >${s}</button></li> `:S+=`<li id="${s}"  class="pg-item" > <button id="${s}" class="pg-num-btn" type="button"
 >${s}</button></li> `;return S})();z.innerHTML=n,x(e.data.results),console.log(y)}).catch(e=>{o.error({message:e.message,position:"topRight"})})}z.addEventListener("click",e=>{p.innerHTML="",console.log(y);const t=e.target.textContent*1;a=q.split(":"),v.defaults.params={page:t,limit:A>1400?"9":"8",muscles:a[0]==="Muscles"?a[1]:null,bodypart:a[0]==="Body parts"?a[1]:null,equipment:a[0]==="Equipment"?a[1]:null},I("/exercises",{params:{}}).then(n=>{x(n.data.results)}).catch(n=>{o.error({message:n.message,position:"topRight"})})});let j;G.addEventListener("input",e=>{j=e.target.value});ye.addEventListener("click",e=>{p.innerHTML="",w.innerHTML="",v.defaults.params={page:1,limit:A>1400?"9":"8",keyword:j,muscles:a[0]==="Muscles"?a[1]:null,bodypart:a[0]==="Body parts"?a[1]:null,equipment:a[0]==="Equipment"?a[1]:null},I("/exercises",{params:{}}).then(t=>{console.log(t.data.totalPages),t.data.totalPages===null&&(me.style.height="100vh",p.innerHTML=`<div class='invalid-name'>${pe}</div>`),x(t.data.results)}).catch(t=>{o.error({message:t.message,position:"topRight"})}).finally(()=>{G.value=""})});function x(e){p.insertAdjacentHTML("afterbegin",e.reduce((t,{burnedCalories:n,name:s,bodyPart:c,rating:d,time:M,target:m,_id:i})=>t+`<li class="waist-gallery-card">
      <div class="header-card">
        <div class="workout">WORKOUT</div>
        <div class="rating">
            <p>${d}</p>
            <svg class="icon-star" width="12" height="12">
                <use href="${L}#icon-star"></use>
            </svg>
        </div>
                 
        <div class="workout-btn-container" data-action="right">
            <button class="workout-btn" id="${i}">Start
            <svg class="icon-right" width="14" height="16">
                <use href="${L}#icon-right"></use>
            </svg>
            </button>
        </div>
      </div>

      <div class="title-card">
          <div class="icon-card">
              <svg class="run" width="24" height="24">
                  <use href="${L}#run"></use>
              </svg>
          </div>
          <h3>${s}</h3>
      </div>

      <ul class="params-card">
            <li class="calories"><span class="params-text">Burned calories:</span> ${n}/${M}min</li>
            <li class="body-part"><span class="params-text">Body part:</span> ${c}</li>
            <li class="target"><span class="params-text">Target:</span> ${m}</li>
      </ul>
    </li>`,"")),te()}const ve=document.querySelector(".footer-form"),Me=document.querySelector(".footer-form-input"),Le="https://energyflow.b.goit.study/api/subscription";ve.addEventListener("submit",Se);async function Se(e){e.preventDefault();const t=e.currentTarget.elements.footerInput.value.trim();if(!Te(t))return Ee();try{const n=await b.post(Le,{email:t});if(n.status>=200&&n.status<300){const s=n.data.message;o.success({title:"OK",message:s,color:"white",position:"center"})}else throw new Error}catch(n){o.error({title:"Error",message:n.response.data.message,position:"center",backgroundColor:"gray"})}finally{Me.value=""}}const Te=e=>/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/.test(e),Ee=()=>{o.info({title:"",message:"Please give us a valid email.",color:"white",position:"center"})},l=[{text:"One-Month Membership",color:"rgba(232, 232, 232, 1)"},{text:"Personal Training Session",color:"rgb(126, 133, 127)"},{text:"Fitness Bracelet",color:"rgba(232, 232, 232, 1)"},{text:"25% Off Certificate",color:"rgb(126, 133, 127)"},{text:"$50 Gift Card",color:"rgba(232, 232, 232, 1)"},{text:"10% Off Certificate",color:"rgb(126, 133, 127)"},{text:"$30 Gift Card",color:"rgba(232, 232, 232, 1)"},{text:"Participation in Marathon",color:"rgb(126, 133, 127)"}],u=document.querySelector(".deal-wheel"),g=u.querySelector(".spinner"),R=u.querySelector(".btn-spin"),$=u.querySelector(".ticker"),we=document.querySelector(".get-prize-container"),B=360/l.length,qe=Math.floor(180/l.length),Y="is-spinning",J="selected",$e=window.getComputedStyle(g);let K,f=0,O=0,H;const Pe=()=>{l.forEach(({text:e,color:t,reaction:n},s)=>{const c=B*s*-1-qe;g.insertAdjacentHTML("beforeend",`<li class="prize" data-reaction=${n} style="--rotate: ${c}deg">
        <span class="text">${e}</span>
      </li>`)})},ke=()=>{g.setAttribute("style",`background: conic-gradient(
      from -90deg,
      ${l.map(({color:e},t)=>`${e} 0 ${100/l.length*(l.length-t)}%`).reverse()}
    );`)},ze=()=>{ke(),Pe(),H=u.querySelectorAll(".prize")},Ae=(e,t)=>(e=Math.ceil(e),t=Math.floor(t),Math.floor(Math.random()*(t-e+1))+e),Z=()=>{const e=$e.transform.split("(")[1].split(")")[0].split(","),t=e[0],n=e[1];let s=Math.atan2(n,t);s<0&&(s+=2*Math.PI);const c=Math.round(s*(180/Math.PI)),d=Math.floor(c/B);O!==d&&($.style.animation="none",setTimeout(()=>$.style.animation=null,10),O=d),K=requestAnimationFrame(Z)},Ie=()=>{const e=Math.floor(f/B);H[e].classList.add(J);const t=l[e].text;setTimeout(()=>{u.style.display="none",introMessagePrize.style.display="none",congratulationsMessage.style.display="block",document.getElementById("congratulationMessage").innerHTML="Congratulations!",document.getElementById("congratulationMessage1").innerHTML=" You've won: ",document.getElementById("prizeMessage").innerText=t,we.style.display="block"},3e3)};R.addEventListener("click",()=>{R.disabled=!0,f=Math.floor(Math.random()*360+Ae(2e3,5e3)),H.forEach(e=>e.classList.remove(J)),u.classList.add(Y),g.style.setProperty("--rotate",f),$.style.animation="none",Z()});g.addEventListener("transitionend",()=>{cancelAnimationFrame(K),f%=360,Ie(),u.classList.remove(Y),g.style.setProperty("--rotate",f)});ze();const xe=document.querySelector("#prizeForm");document.querySelector(".input-get");xe.addEventListener("submit",Be);async function Be(e){e.preventDefault();const t=e.currentTarget.elements.prizeInput.value.trim();if(!He(t))return Ce()}const He=e=>/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/.test(e),Ce=()=>{o.info({title:"",message:"Please give us a valid email.",color:"white",position:"center"})};var C=document.getElementById("myModalPrize"),De=document.getElementById("openModalBtnPrize");De.onclick=function(){C.style.display="flex"};function X(){C.style.display="none"}window.onclick=function(e){e.target==C&&X()};var Re=document.getElementById("closeModalPrize");Re.onclick=function(){X()};document.addEventListener("DOMContentLoaded",function(){function e(){var s=document.getElementById("email-prize").value,c=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!c.test(s)){o.error({title:"Error",message:"Enter a valid email!",zIndex:1001,timeout:2e3,backgroundColor:"white",color:"black",iconColor:"black"});return}o.success({title:"Success",message:"Form submitted!",zIndex:1001,timeout:2e3,backgroundColor:"white",color:"black",iconColor:"black"}),setTimeout(function(){t()},1e3)}function t(){var s=document.getElementById("myModalPrize");s.style.display="none"}var n=document.querySelector(".button-get");n.addEventListener("click",e)});
//# sourceMappingURL=commonHelpers2.js.map
